GET http://localhost/IVMS-API/API/tour/getSampleCompanyData.php
###
GET http://localhost/IVMS-API/API/tour/getCompanyTours.php
###
GET http://localhost/IVMS-API/API/tour/getSampleData.php
###
GET http://localhost/IVMS-API/API/company/getAllCompanies.php
###
POST http://localhost/IVMS-API/API/tour/postNewTour.php
Content-Type: application/json

{
    "name": "FF Tour",
    "branch": "Mechanical",
    "company_id": 1,
    "available_days": "06-11-2020",
    "place": "Delhi",
    "number_people": 5,
    "rate": 100000,
    "description": "Tour."
}

###

GET http://localhost/IVMS-API/API/company/getHomeCompany.php

###
GET http://localhost/IVMS-API/API/tour/getHomeTour.php

###
PUT http://localhost/IVMS-API/API/tour/putEditTour.php
Content-Type: application/json

{
    "name": "Edited Tour Name",
    "branch": "Comps",
    "available_days": "12-11-2020",
    "place": "Kharghar",
    "number_people": 20,
    "rate": 50000,
    "description": "This tour has been edited.",
    "tour_id": 15
}

###
PUT http://localhost/IVMS-API/API/company/putCompanyDetails.php
Content-Type: application/json

{
    "company_id": 2,
    "phone_number": 9876543210,
    "company": "Edited Company",
    "description": "This description has been edited.",
    "email": "edited@api.com"
}

###

POST http://localhost/IVMS-API/API/student/postStudentDetails.php
Content-Type: application/json

{
    "studet_id": "45",
    "user_id": 1,
    "name": "qwerty",
    "email": "asd@wer",
    "phone_number": "1232343454",
    "branch": "Computers"   
}

####

POST http://localhost/IVMS-API/API/tour/postCoordinatorBookedTour.php
Content-Type: application/json

{
    "btour_id": "1",
    "tour_id": "1",
    "user_id": 2,
    "number_people":10,
    "date": "12-1-21",
    "rating": 5,

}