GET http://localhost/IVMS-API/API/tour/getSampleCompanyData.php
###
GET http://localhost/IVMS-API/API/tour/getSampleData.php
###
GET http://localhost/IVMS-API/API/company/getAllCompanies.php
###
POST http://localhost/IVMS-API/API/tour/postNewTour.php
Content-Type: application/json

{
    "name": "ABC Tour",
    "branch": "IT",
    "company_id": 1,
    "available_days": "17-09-2020",
    "place": "Mumbai",
    "number_people": 10,
    "number_days": 31,
    "rate": 1000,
    "description": "akdajsdasd"
}

###
GET http://localhost/IVMS-API/API/company/getHomeData.php