GET http://localhost/IVMS-API/API/tour/getSampleCompanyData.php
###
GET http://localhost/IVMS-API/API/tour/getCompanyTours.php
###
GET http://localhost/IVMS-API/API/tour/getSampleData.php
###
GET http://localhost/IVMS-API/API/company/getAllCompanies.php
###
POST http://localhost/IVMS-API/API/tour/postNewTour.php
Content-Type: application/json

{
    "name": "ABC Tour",
    "branch": "IT",
    "company_id": 1,
    "available_days": "02-10-2020",
    "place": "Mumbai",
    "number_people": 10,
    "rate": 1000,
    "description": "via API"
}

###

GET http://localhost/IVMS-API/API/company/getHomeCompany.php

###
GET http://localhost/IVMS-API/API/tour/getHomeTour.php

###

POST http://localhost/IVMS-API/API/company/postUserCompany.php
Content-Type: application/json

{
    
    "email": "vgty@gmail.com",
    "password": 1578,
    "phone_number": 8765475631,
    "company": "hhu",
    "description": "jhfghuguehjhfbwfj"
}

###

POST http://localhost/IVMS-API/API/coordinator/postUserCoordinator.php 
Content-Type: application/json

{
"email": "abc@def.com", 
"password": "hashed", 
"phone_number": "1234", 
"college": "ABC College"
}

### 

GET http://localhost/IVMS-API/API/company/getHashCompany.php

###

GET http://localhost/IVMS-API/API/coordinator/getHashCoordinator.php